name: Update Pairings File

on:
  repository_dispatch:
    types: [update-pairings]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update pairings.json
        run: |
          echo '${{ github.event.client_payload.pairings }}' > pairings.json

      - name: Commit & Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "FPG Auto Bot"
          git config user.email "noreply@floridaplayersgroup.com"
          git add pairings.json
          git commit -m "ğŸ” Updated pairings via dashboard"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main
